### PR TITLE
Bump gitbucket to 4.35.0

### PR DESCRIPTION
**Pull request by onukura**
related to #25

### CODE REVIEW

**Comment by yoshinorin** [comment]
@onukura 
Thank you :)

Do you have any plan to put `war` file on to [release page](https://github.com/gitbucket/gitbucket/releases)?
I want to use it for testing.

**Comment by onukura** [comment]
@YoshinoriN I don't have plan to put war file...
actually I'm testing with master branch because code for v4.35.0 is almost fixed. Maybe you can use GitHub action's artifacts [here](https://github.com/gutbucket/gitbucket/actions/runs/424926470)!
This is latest war of commit of master branch.

**Comment by onukura** [comment]
@YoshinoriN 
Now GitBucket v4.35.0 officially available on the release page.

**Comment by yoshinorin** [comment]
@onukura 
Thank you as well :)

**Pull request merged**
